import { opendir,readFile,stat } from "node:fs/promises";
import { dirname,extname,normalize,relative,resolve,sep } from "node:path";

export const DEFAULT_IGNORES=['.git','node_modules','dist','build','coverage','.cache'];
const TEXT_EXTENSIONS=new Set(['.js','.mjs','.cjs','.ts','.tsx','.jsx','.json','.html','.htm','.css','.md','.mdx','.yml','.yaml','.py','.java','.go','.rs','.php','.rb','.sh','.txt']);
const SOURCE_TYPES={'.js':'javascript','.mjs':'javascript','.cjs':'javascript','.ts':'typescript','.tsx':'typescript','.jsx':'javascript','.html':'html','.htm':'html','.css':'css','.json':'json','.md':'markdown','.mdx':'markdown','.yml':'yaml','.yaml':'yaml','.py':'python','.java':'java','.go':'go','.rs':'rust','.php':'php','.rb':'ruby','.sh':'shell','.txt':'text'};
const unique=list=>[...new Set(list.filter(Boolean))];
export const isBinary=buffer=>buffer.subarray(0,8192).includes(0);
export function languageFor(path){return SOURCE_TYPES[extname(path).toLowerCase()]??'other'}
export function parseReferences(path,text){const extension=extname(path).toLowerCase(),references=[];const add=(kind,value)=>{const raw=String(value??'').trim();if(raw&&!raw.startsWith('#')&&!raw.startsWith('data:'))references.push({kind,raw})};if(['.js','.mjs','.cjs','.ts','.tsx','.jsx'].includes(extension)){for(const match of text.matchAll(/(?:import\s+(?:[^'";]+?\s+from\s+)?|export\s+[^'";]+?\s+from\s+|require\s*\(|import\s*\()\s*['"]([^'"]+)['"]/g))add('import',match[1])}if(['.html','.htm'].includes(extension)){for(const match of text.matchAll(/(?:href|src)\s*=\s*['"]([^'"]+)['"]/gi))add('html-link',match[1])}if(extension==='.css'){for(const match of text.matchAll(/(?:url\(\s*['"]?|@import\s+['"])([^'"\s)]+)/gi))add('css-reference',match[1])}if(['.md','.mdx'].includes(extension)){for(const match of text.matchAll(/!?\[[^\]]*\]\(([^)\s]+)(?:\s+[^)]*)?\)/g))add('readme-link',match[1])}if(extension==='.json'){try{const walk=value=>{if(typeof value==='string'&&(/^(?:\.\.?\/|\/)/.test(value)||/\.(?:json|js|ts|css|html|md|pdf|svg|png|jpg)$/i.test(value)))add('json-reference',value);else if(Array.isArray(value))value.forEach(walk);else if(value&&typeof value==='object')Object.values(value).forEach(walk)};walk(JSON.parse(text))}catch{}}if(['.yml','.yaml'].includes(extension)&&/\.github[\\/]+workflows/.test(path)){for(const match of text.matchAll(/\buses:\s*([^\s#]+)/g))add('workflow-use',match[1])}return unique(references.map(item=>JSON.stringify(item))).map(item=>JSON.parse(item))}
export async function listRepositoryFiles(root,{ignores=DEFAULT_IGNORES,limit=30000}={}){const target=resolve(root);if(target===sep)throw new Error('Refusing to map the filesystem root. Select a repository folder.');const result=[],skipped=[],stack=[target];while(stack.length){const folder=stack.pop();let handle;try{handle=await opendir(folder)}catch(error){skipped.push({path:relative(target,folder),reason:error.code??'unreadable'});continue}for await(const entry of handle){const full=resolve(folder,entry.name),rel=relative(target,full);if(rel.split(sep).some(part=>ignores.includes(part))){skipped.push({path:rel,reason:'ignored'});continue}if(entry.isSymbolicLink()){skipped.push({path:rel,reason:'symlink-not-followed'});continue}if(entry.isDirectory()){stack.push(full);continue}if(!entry.isFile())continue;if(result.length>=limit)throw new Error(`File limit ${limit} reached; narrow the scope or add ignores.`);const info=await stat(full);result.push({path:rel,absolute:full,extension:extname(rel).toLowerCase(),language:languageFor(rel),bytes:info.size,modifiedAt:info.mtimeMs})}}return{root:target,files:result.sort((a,b)=>a.path.localeCompare(b.path)),skipped}}
export async function readTextFile(file,{maxBytes=2*1024*1024}={}){if(!TEXT_EXTENSIONS.has(file.extension)||file.bytes>maxBytes)return null;const buffer=await readFile(file.absolute);if(isBinary(buffer))return null;return buffer.toString('utf8')}
export function resolveReference(from,raw,filePaths){const clean=raw.split(/[?#]/)[0].replace(/\\/g,'/');if(!clean||/^(?:https?:|mailto:|tel:|npm:)/i.test(clean))return{target:`external:${raw}`,external:true};const direct=(clean.startsWith('/')?clean.slice(1):normalize(`${dirname(from)}/${clean}`)).replace(/\\/g,'/');const candidates=[direct,`${direct}.js`,`${direct}.mjs`,`${direct}.ts`,`${direct}.tsx`,`${direct}.json`,`${direct}.html`,`${direct}.css`,`${direct}.md`,`${direct}/index.js`,`${direct}/index.ts`];const found=candidates.find(candidate=>filePaths.has(candidate));return found?{target:found,external:false}:{target:`unresolved:${raw}`,external:true}}
