import { mkdir,writeFile } from "node:fs/promises";
import { join,resolve } from "node:path";

const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

const clientScript=String.raw`(()=>{
  const twin=JSON.parse(document.getElementById('data').textContent);
  const graph=document.getElementById('graph'),results=document.getElementById('results'),detail=document.getElementById('detail');
  const search=document.getElementById('search'),kind=document.getElementById('kind'),risk=document.getElementById('risk');
  const esc=value=>{const node=document.createElement('span');node.textContent=String(value??'');return node.innerHTML};
  const incoming=id=>twin.edges.filter(edge=>edge.target===id),outgoing=id=>twin.edges.filter(edge=>edge.source===id);
  function candidates(){const term=search.value.toLowerCase();return twin.nodes.filter(node=>(!term||node.id.toLowerCase().includes(term)||node.label.toLowerCase().includes(term))&&(!kind.value||node.kind===kind.value)&&(!risk.value||twin.degrees[node.id]?.risk===risk.value))}
  function coords(index,total){const angle=Math.PI*2*index/Math.max(total,1),radius=Math.min(190,72+total*2);return{x:450+Math.cos(angle)*radius,y:245+Math.sin(angle)*radius}}
  function selectNode(id){const node=twin.nodes.find(item=>item.id===id);if(!node)return;const inward=incoming(id),outward=outgoing(id),pages=inward.filter(edge=>/\.html?$/i.test(edge.source)).map(edge=>edge.source);const affected=[],queue=[id],seen=new Set([id]);while(queue.length){const target=queue.shift();for(const edge of incoming(target))if(!seen.has(edge.source)){seen.add(edge.source);queue.push(edge.source);affected.push(edge.source)}}const nl=String.fromCharCode(10);detail.innerHTML='<b>'+esc(node.id)+'</b>'+nl+'Kind: '+esc(node.kind)+' · Risk: '+esc(twin.degrees[node.id]?.risk??'low')+nl+'Incoming references: '+inward.length+nl+'Outgoing references: '+outward.length+nl+'Pages using this node: '+(pages.length?esc(pages.join(', ')):'none identified')+nl+nl+'Potential rename impact ('+affected.length+' static dependent(s)): '+(affected.length?esc(affected.join(', ')):'none identified')+nl+nl+'Plan: review direct dependents, update static references intentionally, rerun the twin, then run the repository’s own tests/build. This tool makes no source changes.';document.querySelectorAll('.item').forEach(item=>item.classList.toggle('active',item.dataset.id===id))}
  function render(){const nodes=candidates(),positions=new Map(nodes.map((node,index)=>[node.id,{node,...coords(index,nodes.length)}]));graph.replaceChildren();for(const edge of twin.edges){const from=positions.get(edge.source),to=positions.get(edge.target);if(!from||!to)continue;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',from.x);line.setAttribute('y1',from.y);line.setAttribute('x2',to.x);line.setAttribute('y2',to.y);line.setAttribute('class','edge risk-'+(twin.degrees[edge.target]?.risk??'low'));graph.append(line)}for(const item of positions.values()){const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',item.x);circle.setAttribute('cy',item.y);circle.setAttribute('r',item.node.kind==='file'?11:9);circle.setAttribute('class','node '+item.node.kind);circle.addEventListener('click',()=>selectNode(item.node.id));const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=item.node.id;circle.append(title);graph.append(circle)}results.innerHTML=nodes.slice(0,120).map(node=>'<div class="item" data-id="'+esc(node.id)+'"><b>'+esc(node.id)+'</b><br><small>'+esc(node.kind)+' · '+esc(twin.degrees[node.id]?.risk??'low')+'</small></div>').join('')||'<p class="muted">No matching nodes.</p>';document.querySelectorAll('.item').forEach(item=>item.addEventListener('click',()=>selectNode(item.dataset.id)))}
  [search,kind,risk].forEach(control=>control.addEventListener('input',render));render();
})();`;

export function reportHtml(twin){
  const payload=JSON.stringify(twin).replace(/</g,'\\u003c');
  const fileRows=twin.nodes.filter(node=>node.kind==='file').slice(0,100).map(node=>`<tr><td>${escape(node.id)}</td><td>${escape(twin.degrees[node.id]?.risk??'low')}</td><td>${twin.degrees[node.id]?.incoming??0} / ${twin.degrees[node.id]?.outgoing??0}</td><td>${escape(node.modifiedAt)}</td></tr>`).join('')||'<tr><td colspan="4">No file nodes.</td></tr>';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project Digital Twin</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#1f2933;background:#eff5f3}body{margin:0}.wrap{max-width:1360px;margin:auto;padding:26px 18px 56px}.hero{padding:30px;border-radius:20px;color:#fff;background:linear-gradient(135deg,#173e4b,#2e735c)}h1,h2{margin:0}.hero p{max-width:880px;line-height:1.5;color:#d8f0e8}.notice{padding:13px;border-radius:10px;background:#fff3dc;color:#6a4b13;line-height:1.47;margin:18px 0;font-size:.88rem}.metrics{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.metric,.panel{padding:15px;border:1px solid #d2e1dc;border-radius:14px;background:#fff;box-shadow:0 6px 18px #16342e0b}.metric b{display:block;color:#17745d;font-size:1.35rem;margin-top:3px}.metric small,.muted{color:#657980}.controls{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.controls input,.controls select{padding:8px;border:1px solid #c8d8d2;border-radius:8px;font:inherit;min-width:140px}.layout{display:grid;grid-template-columns:1fr 360px;gap:16px;margin-top:16px}.graph{width:100%;min-height:490px;background:radial-gradient(circle at 50% 40%,#f3fbf8,#fff);border-radius:10px}.node{cursor:pointer}.node.file{fill:#34846f}.node.external{fill:#d38b40}.node.package{fill:#7963b2}.edge{stroke:#8bb5a8;stroke-opacity:.55}.risk-high{stroke:#c43d36;stroke-width:3}.risk-medium{stroke:#d19336;stroke-width:2}.detail{white-space:pre-wrap;line-height:1.5;font-size:.88rem;min-height:260px}.badge{display:inline-block;padding:3px 6px;border-radius:99px;background:#e5f4ee;color:#176b56;font-size:.72rem}.list{max-height:260px;overflow:auto;margin-top:10px}.item{padding:8px;border-bottom:1px solid #e4eeea;cursor:pointer;overflow-wrap:anywhere}.item:hover,.item.active{background:#eff9f5}.table{width:100%;border-collapse:collapse;font-size:.82rem;margin-top:10px}.table th,.table td{text-align:left;vertical-align:top;padding:8px;border-bottom:1px solid #e2ece8;overflow-wrap:anywhere}.table th{color:#61767c}@media(max-width:980px){.metrics{grid-template-columns:repeat(3,1fr)}.layout{grid-template-columns:1fr}}@media(max-width:520px){.wrap{padding:14px 11px 40px}.metrics{grid-template-columns:1fr 1fr}.controls input,.controls select{width:100%}}
</style></head><body><main class="wrap"><header class="hero"><h1>Project Digital Twin</h1><p>Read-only local architecture map of folders, files, static references, package metadata, workflows, and available Git activity. It creates a normalized graph without modifying the selected repository.</p></header><p class="notice"><strong>Static-analysis limitation:</strong> dynamic imports, generated paths, aliases, runtime routing, reflection, unsupported syntax, and external resources can be incomplete. Nodes/edges are review evidence, not a complete execution model or an automatic rename plan.</p><section class="metrics"><article class="metric"><small>Files</small><b>${twin.summary.files}</b></article><article class="metric"><small>Nodes</small><b>${twin.summary.nodes}</b></article><article class="metric"><small>References</small><b>${twin.summary.edges}</b></article><article class="metric"><small>External nodes</small><b>${twin.summary.externalNodes}</b></article><article class="metric"><small>Orphan hints</small><b>${twin.summary.orphans}</b></article><article class="metric"><small>Recent files</small><b>${twin.summary.recent}</b></article></section><section class="panel"><h2>Interactive graph</h2><div class="controls"><input id="search" placeholder="Search nodes"><select id="kind"><option value="">All node types</option><option value="file">Files</option><option value="package">Packages</option><option value="external">External/unresolved</option></select><select id="risk"><option value="">All risk levels</option><option value="high">High impact</option><option value="medium">Medium impact</option><option value="low">Low impact</option></select></div><div class="layout"><svg id="graph" class="graph" viewBox="0 0 900 500" role="img" aria-label="Interactive project dependency graph"></svg><aside class="panel"><h2>Node details / impact plan</h2><div id="detail" class="detail muted">Select a graph node or list item to inspect incoming/outgoing references, pages using the node, and a read-only rename impact plan.</div><h2 style="margin-top:15px">Search results</h2><div id="results" class="list"></div></aside></div></section><section class="panel"><h2>Architecture review hints</h2><p><span class="badge">${twin.orphans.length} orphan hint(s)</span> <span class="badge">${twin.stale.length} stale resource hint(s)</span> <span class="badge">${twin.recent.length} recently changed file(s)</span></p><table class="table"><thead><tr><th>File</th><th>Risk</th><th>Incoming / outgoing</th><th>Modified</th></tr></thead><tbody>${fileRows}</tbody></table></section></main><script id="data" type="application/json">${payload}</script><script>${clientScript}</script></body></html>`;
}

export async function writeReport(twin,out){
  const target=resolve(out),html=join(target,'project-digital-twin.html'),json=join(target,'project-digital-twin.json');
  await mkdir(target,{recursive:true});
  await writeFile(html,reportHtml(twin));
  await writeFile(json,JSON.stringify(twin,null,2)+'\n');
  return{html,json};
}
