import { execFile } from "node:child_process";
import { basename,relative,resolve } from "node:path";
import { listRepositoryFiles,parseReferences,readTextFile,resolveReference } from "./adapters.mjs";

const git=(cwd,args)=>new Promise(resolveRun=>execFile('git',['-C',cwd,...args],(error,stdout)=>resolveRun(error?null:stdout.trim())));
const risk=value=>value>=12?'high':value>=5?'medium':'low';
export async function buildTwin(root,{ignores=[],recentDays=30,staleDays=365}={}){const inventory=await listRepositoryFiles(root,{ignores:ignores.length?ignores:undefined});const filePaths=new Set(inventory.files.map(file=>file.path));const nodes=inventory.files.map(file=>({id:file.path,label:basename(file.path),kind:'file',language:file.language,bytes:file.bytes,modifiedAt:new Date(file.modifiedAt).toISOString()}));const edges=[],nodeIds=new Set(nodes.map(node=>node.id));const addNode=node=>{if(!nodeIds.has(node.id)){nodeIds.add(node.id);nodes.push(node)}};for(const file of inventory.files){const text=await readTextFile(file);if(text===null)continue;for(const ref of parseReferences(file.path,text)){const resolved=resolveReference(file.path,ref.raw,filePaths);addNode({id:resolved.target,label:resolved.target.replace(/^(?:external|unresolved):/,''),kind:resolved.external?'external':'file',language:'external'});edges.push({source:file.path,target:resolved.target,kind:ref.kind,raw:ref.raw})}if(file.path==='package.json'){try{const pkg=JSON.parse(text);for(const[name,version]of Object.entries({...pkg.dependencies,...pkg.devDependencies})){const id=`package:${name}`;addNode({id,label:name,kind:'package',version:String(version),language:'package'});edges.push({source:file.path,target:id,kind:'package-dependency',raw:String(version)})}}catch{}}}const gitHistory=await git(inventory.root,['log','--all','--format=%aI%x1f%H%x1f%an%x1f%s','--name-only']);const recent=new Set();if(gitHistory){const cutoff=Date.now()-recentDays*86400000;for(const block of gitHistory.split('\n\n')){const [header,...paths]=block.split('\n'),[date,hash,author,subject]=header.split('\x1f');if(Date.parse(date)>=cutoff)for(const path of paths.filter(Boolean))recent.add(path)}}const twin={schemaVersion:'project-digital-twin/v1',createdAt:new Date().toISOString(),root:inventory.root,nodes,edges,skipped:inventory.skipped,options:{recentDays,staleDays,ignores},gitHistoryAvailable:Boolean(gitHistory),disclaimer:'Read-only static analysis. No source, Git, package, workflow, or repository state is changed. Dynamic imports, generated files, runtime routing, aliases, reflection, and unsupported language syntax may be incomplete.'};return analyzeTwin(twin,recent)}
export function analyzeTwin(twin,recentPaths=new Set()){const incoming=new Map(),outgoing=new Map();for(const edge of twin.edges){const input=incoming.get(edge.target)??[];input.push(edge);incoming.set(edge.target,input);const output=outgoing.get(edge.source)??[];output.push(edge);outgoing.set(edge.source,output)}const staleCutoff=Date.now()-twin.options.staleDays*86400000;const files=twin.nodes.filter(node=>node.kind==='file');const orphans=files.filter(node=>!(incoming.get(node.id)?.length)&&!(outgoing.get(node.id)?.length));const stale=files.filter(node=>Date.parse(node.modifiedAt)<staleCutoff);const recent=files.filter(node=>recentPaths.has(node.id));const degrees=Object.fromEntries(files.map(node=>[node.id,{incoming:(incoming.get(node.id)??[]).length,outgoing:(outgoing.get(node.id)??[]).length,risk:risk((incoming.get(node.id)??[]).length+(outgoing.get(node.id)??[]).length)}]));return{...twin,summary:{files:files.length,nodes:twin.nodes.length,edges:twin.edges.length,externalNodes:twin.nodes.filter(node=>node.kind!=='file').length,orphans:orphans.length,stale:stale.length,recent:recent.length},degrees,orphans,stale,recent}}
export function queryTwin(twin,path){const incoming=twin.edges.filter(edge=>edge.target===path),outgoing=twin.edges.filter(edge=>edge.source===path);return{node:twin.nodes.find(node=>node.id===path)??null,dependsOn:outgoing,dependents:incoming,pagesUsing:twin.edges.filter(edge=>edge.target===path&&/\.html?$/i.test(edge.source)).map(edge=>edge.source),references:incoming,risk:twin.degrees?.[path]?.risk??'low'}}
export function impactPlan(twin,path){const queue=[path],visited=new Set([path]),affected=[];while(queue.length){const target=queue.shift();for(const edge of twin.edges.filter(item=>item.target===target)){if(!visited.has(edge.source)){visited.add(edge.source);queue.push(edge.source);affected.push(edge.source)}}}return{path,directDependents:twin.edges.filter(edge=>edge.target===path).map(edge=>edge.source),affected,level:risk(affected.length),plan:['Review direct dependents before renaming or moving the file.','Update static references identified by the twin and rerun the local analysis.','Run the repository’s own tests/build; this tool does not execute project code.']}}
export function compareTwins(baseline,current){const supported=new Set(['project-digital-twin/v1','project-digital-twin-snapshot/v1']);if(!supported.has(baseline?.schemaVersion)||!supported.has(current?.schemaVersion))throw new Error('Both inputs must be Project Digital Twin analysis documents or saved twin snapshots.');const before=new Set(baseline.nodes.map(node=>node.id)),after=new Set(current.nodes.map(node=>node.id));return{baselineAt:baseline.createdAt,currentAt:current.createdAt,addedNodes:[...after].filter(id=>!before.has(id)),removedNodes:[...before].filter(id=>!after.has(id)),edgeDelta:current.edges.length-baseline.edges.length,fileDelta:current.summary.files-baseline.summary.files}}
export function createSnapshot(twin){return{schemaVersion:'project-digital-twin-snapshot/v1',createdAt:new Date().toISOString(),root:twin.root,summary:twin.summary,nodes:twin.nodes,edges:twin.edges,options:twin.options}}
